### ISSUE TITLE
ios 错误

### ISSUE THREAD

**Issue by cacolargit** [log2c/cordova-plugin-aliyunpush#1]
请问执行 AliPushPlugin.init() 时会显示 Method '_init:' not defined in Plugin 'AliPushPlugin' 错误是甚么问题？

**Comment by log2c** [comment]
> 请问执行 AliPushPlugin.init() 时会显示 Method '_init:' not defined in Plugin 'AliPushPlugin' 错误是甚么问题？

有没有截图或者具体的信息，我不是很懂为什么会有这问题，我代码里没有这用法呀？

**Comment by cacolargit** [comment]
不好意思我弄错外挂了，你的可以正常使用，谢谢您！
