### ISSUE TITLE
请教一下在Ionic下如何使用插件

### ISSUE THREAD

**Issue by dythbj** [log2c/cordova-plugin-aliyunpush#11]
您好，请教一下在ionic下如何使用插件，我现在是这么用的：
![image](https://user-images.githubusercontent.com/41282663/91381395-e2060480-e859-11ea-89f3-a4fdec7f4978.png)
您看是这么使用的吗？

**Comment by dythbj** [comment]
这个是app.component.ts的代码，onMessage是不是就是收到推送了啊？

**Comment by log2c** [comment]
> 这个是app.component.ts的代码，onMessage是不是就是收到推送了啊？

参考 README "ionic中使用(可选)"

**Comment by dythbj** [comment]
> > 这个是app.component.ts的代码，onMessage是不是就是收到推送了啊？
> 
> 参考 README "ionic中使用(可选)"

知道了，谢谢
