### ISSUE TITLE
可以接收到推送，但是不显示消息弹窗

### ISSUE THREAD

**Issue by coloz** [log2c/cordova-plugin-aliyunpush#3]
在阿里后台，发送通知，可以接收到，但状态栏没有通知，求帮助

**Comment by log2c** [comment]
> 在阿里后台，发送通知，可以接收到，但状态栏没有通知，求帮助

设置里开启App"横幅"通知的权限即可

**Comment by coloz** [comment]
您是说的android系统设置里的横幅通知权限么？我确认已开启，但显示不出来

**Comment by log2c** [comment]
具体型号发来看下。
看你说明，状态栏没通知，只有可能你发的不是通知，而是消息。
这个库本身没有处理通知的逻辑，具体可以去阿里提交工单。

**Comment by log2c** [comment]
> 您是说的android系统设置里的横幅通知权限么？我确认已开启，但显示不出来

具体型号发来看下。
看你说明，状态栏没通知，只有可能你发的不是通知，而是消息。
这个库本身没有处理通知的逻辑，具体可以去阿里提交工单。

**Comment by coloz** [comment]
发的是通知，而且消息也试了。手机为三星S9（android9）、华为mate30pro(android10)  
感谢您的回复。

**Comment by coloz** [comment]
是我服务器端推送时没有setAndroidNotificationChannel造成的。感谢您的插件和耐心解答。
