### ISSUE TITLE
使用该插件后，上架被拒，提示有隐藏支付宝API

### ISSUE THREAD

**Issue by coloz** [log2c/cordova-plugin-aliyunpush#5]
被拒信息如下：
```
Guideline 2.3.1 - Performance


We discovered that your app contains hidden features. Attempting to hide features, functionality or content in your app is considered egregious behavior and can lead to removal from the Apple Developer Program.

Specifically, we found that your app includes AliPay (支付寶), which provides access to external payment mechanisms and enables the purchase of content, services, or functionality by means other than the in-app purchase API.

If you feel that we have misunderstood how your app functions and that your app is compliant with the App Store Review Guidelines, please reply to this message in Resolution Center to explain how this feature works.

The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.

Next Steps

- Review the Performance section of the App Store Review Guidelines.
- Ensure your app, as well as any third-party code and SDKs implemented in your app, are compliant with all sections of the App Store Review Guidelines and the Terms & Conditions of the Apple Developer Program.
- Revise or remove the hidden features from your app. Once your app is fully compliant, resubmit your app for review.

Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the Terms & Conditions of the Apple Developer Program to learn more about our policies regarding termination.

```

**Comment by log2c** [comment]
> 被拒信息如下：
> 
> ```
> Guideline 2.3.1 - Performance
> 
> 
> We discovered that your app contains hidden features. Attempting to hide features, functionality or content in your app is considered egregious behavior and can lead to removal from the Apple Developer Program.
> 
> Specifically, we found that your app includes AliPay (支付寶), which provides access to external payment mechanisms and enables the purchase of content, services, or functionality by means other than the in-app purchase API.
> 
> If you feel that we have misunderstood how your app functions and that your app is compliant with the App Store Review Guidelines, please reply to this message in Resolution Center to explain how this feature works.
> 
> The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.
> 
> Next Steps
> 
> - Review the Performance section of the App Store Review Guidelines.
> - Ensure your app, as well as any third-party code and SDKs implemented in your app, are compliant with all sections of the App Store Review Guidelines and the Terms & Conditions of the Apple Developer Program.
> - Revise or remove the hidden features from your app. Once your app is fully compliant, resubmit your app for review.
> 
> Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the Terms & Conditions of the Apple Developer Program to learn more about our policies regarding termination.
> ```
> 
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)

我只引入了阿里云推送要求的framework，具体你提交阿里云工单，问他们什么情况吧

![SDK文档](https://raw.githubusercontent.com/log2c/pic-repos/master/img/20200506095214.png?token=ACMC4SV7H7AWCLMMNMFGO3K6WIMIY)

![项目依赖](https://raw.githubusercontent.com/log2c/pic-repos/master/img/20200506095243.png?token=ACMC4SSQ5Z2L5FOLNNPIYHK6WIMKS)
