### ISSUE TITLE
在Ionic中使用了推荐的初始化，但是没有执行 initPushService(this) 这个方法

### ISSUE THREAD

**Issue by jombLiu** [log2c/cordova-plugin-aliyunpush#6]
在Ionic中使用了推荐的初始化，但是没有执行 initPushService(this) 这个方法， 导致推送通知不成功

**Comment by jombLiu** [comment]
如果有Ionic的使用方式， 麻烦给下地址

**Comment by coloz** [comment]
https://github.com/log2c/cordova-plugin-log2c-aliyun-push/tree/%40ionic-native

**Comment by jombLiu** [comment]
目前主要的问题还是不能推送执行初始化

**Comment by log2c** [comment]
> 在Ionic中使用了推荐的初始化，但是没有执行 initPushService(this) 这个方法， 导致推送通知不成功

用哪个方法初始化? 方法一的话，检查`AndroidManifest.xml`的 `application`节点是否成功添加了 `android:name="com.alipush.PushApplication" `

**Comment by jombLiu** [comment]
有几个问题质询下：见下图
![image](https://user-images.githubusercontent.com/30170813/87420825-86b0e780-c608-11ea-8ec6-82462a179249.png)
这块的value还都是变量，有问题

**Comment by jombLiu** [comment]
还有一个问题是

Android 在app进程关闭的情况下，配置辅助推送后可以收到通知， 但是 点击通知打不开App, 这块的activity应该怎样配置？
**[以上的所有问题都是基于Ionic5+capacitor+angular9 去实现的]**

**Comment by jombLiu** [comment]
![image](https://user-images.githubusercontent.com/30170813/87421827-27ec6d80-c60a-11ea-8100-a6be7d70b662.png)
还有一个问题是,Android 在app进程关闭的情况下，配置辅助推送后可以收到通知， 但是 点击通知打不开App, 这块的activity应该怎样配置？
[以上的所有问题都是基于Ionic5+capacitor+angular9 去实现的]

**Comment by log2c** [comment]
> 有几个问题质询下：见下图
> ![image](https://user-images.githubusercontent.com/30170813/87420825-86b0e780-c608-11ea-8ec6-82462a179249.png)
> 这块的value还都是变量，有问题

你的怎么是 capacitor? 我只测试了 Cordova 环境。

meta 标签变量不变问题估计也是因为这个的问题，或者是因为 命令行传参错误导致的。

点击不打开App的问题是因为后台推送参数导致的，参考 
https://github.com/log2c/cordova-plugin-log2c-aliyun-push/blob/0eba7ac38158be3ac916329d66612c7c8b497907/src/android/PopupPushActivity.java#L55


![](https://raw.githubusercontent.com/log2c/pic-repos/master/img/20200715153725.png)

**Comment by jombLiu** [comment]
感谢回复！
