### ISSUE TITLE
Could not find method implementation() for arguments [com.android.support:support-compat:27.+]

### ISSUE THREAD

**Issue by dythbj** [log2c/cordova-plugin-aliyunpush#9]
您好：
        Android编译的时候报错：
        * Where:
Script '/Users/gaojie/Library/Develop/ionic/SurveySPB/platforms/android/cordova-plugin-log2c-aliyun-push/surveyspb-build-extras.gradle' line: 19

* What went wrong:
A problem occurred evaluating script.
> Could not find method implementation() for arguments [com.android.support:support-compat:27.+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

请教大神如何处理？

**Comment by log2c** [comment]
> 您好：
> Android编译的时候报错：
> * Where:
> Script '/Users/gaojie/Library/Develop/ionic/SurveySPB/platforms/android/cordova-plugin-log2c-aliyun-push/surveyspb-build-extras.gradle' line: 19
> 
> * What went wrong:
>   A problem occurred evaluating script.
> 
> > Could not find method implementation() for arguments [com.android.support:support-compat:27.+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> 请教大神如何处理？

看样子是项目的 Gradle 版本太低，需要升级

**Comment by dythbj** [comment]
我把implementation 'com.android.support:support-compat:27.+'改成了compile 'com.android.support:support-compat:27.+'，但是现在报AliyunPush.java:83: 错误: -source 1.6 中不支持 lambda 表达式cordova.getThreadPool().execute(() -> {

**Comment by log2c** [comment]
> 我把implementation 'com.android.support:support-compat:27.+'改成了compile 'com.android.support:support-compat:27.+'，但是现在报AliyunPush.java:83: 错误: -source 1.6 中不支持 lambda 表达式cordova.getThreadPool().execute(() -> {

你Cordova 版本升级到 9 吧，应该就可以了

**Comment by dythbj** [comment]
> > 我把implementation 'com.android.support:support-compat:27.+'改成了compile 'com.android.support:support-compat:27.+'，但是现在报AliyunPush.java:83: 错误: -source 1.6 中不支持 lambda 表达式cordova.getThreadPool().execute(() -> {
> 
> 你Cordova 版本升级到 9 吧，应该就可以了

好的，谢谢
